twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        carousel: '@App\Service\Carousel'
        userPanel: '@App\Service\UserPanel'
        container: '@service_container'
